---
title: "Factor analysis"
output: html_notebook
---
```{r}
### 諸々設定(最初だけ)
install.packages(c("psych", "rgl", "plotly"))
```

```{r}
### データ読み込み
dat <- read.csv(file('data/factor_analysis.csv',encoding="Shift_JIS"), header=TRUE)
dat <- dat[,-1]
colnames(dat)<-c("硬い","騒がしい","熱い","重い","強い","明るい","鋭い","美しい","良い","動いている","派手な","面白い","積極的な")
rownames(dat)<-c("鮮やかな赤",
                 "明るい赤",
                 "暗い赤",
                 "ごく暗い赤",
                 "鮮やかな???",
                 "薄い???",
                 "くすんだ黄",
                 "ごく暗い黄",
                 "濃い緑",
                 "明るい緑",
                 "灰みの緑",
                 "ごく暗い緑",
                 "鮮やかな緑みの青",
                 "明るい緑みの青",
                 "濃い緑みの青",
                 "ごく暗い緑みの青",
                 "白",
                 "灰色",
                 "黒"
)

```

```{r}
### 記述統計
library(psych)
as.data.frame(describe(dat))
```

```{r}
### 変数間の相関係数の確認
# そこまで気にしないで良い
as.data.frame(round(cor(dat),3)) # 相関行列

```

```{r}
### スクリープロット 
## 固有値が1以上または角度が急な部分までを因子の数にする(今回は4あたり)
library(psych)
pairs.panels(dat)
VSS.scree(dat)

```

```{r}
### 固有値を確認
## そこまで気にしないで良い
corx <- cor(dat)
print("固有値")
eigen(corx)$values # 固有値

## 説明された分散の%（寄与率）
print("寄与率")
eigen(corx)$values/sum(eigen(corx)$values)

```

```{r}
### 因子分析
efa <- factanal(dat, factors=3, scores="regression", rotation="promax")
common <- 1-efa$uniqueness
common
print(efa, cutoff=0)


# Uniqusness:変数の独自性
# loading:因子負荷量
# Proportion Var:寄与率
# Cumulative Var:累積寄与率
# 因子負荷量：各形容詞に対する因子の係数的なやつ
# 因子分析をするコードにはfaやfactanalがあるけど、faについては赤本参照

# 保存する際は以下
# write.csv(efa$loadings, "loadings.csv", row.names=T)

```

```{r}
####因子負荷量の棒グラフ####
oldpar<-par(no.readonly = TRUE)
#par(mfrow = c(1,3))
barplot(efa$loadings[,1], main="Factor1", ylim=c(-1,1))
barplot(efa$loadings[,2], main="Factor2", ylim=c(-1,1))
barplot(efa$loadings[,3], main="Factor3", ylim=c(-1,1))
par(oldpar)

```

```{r}
### 因子負荷量のプロット
plot(efa$loadings[,1:2], type="n", xlim=c(-1,1), ylim=c(-1,1))
# arrows(0,0,efa$loadings[,1],efa$loadings[,2])
# 矢印を表示させたければこんな感じのコードを入れる（今回は省略）
text(efa$loadings[,1:2], colnames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)

plot(efa$loadings[,2:3], type="n", xlim=c(-1,1), ylim=c(-1,1))
text(efa$loadings[,2:3], colnames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)

plot(efa$loadings[,-2], type="n", xlim=c(-1,1), ylim=c(-1,1))
text(efa$loadings[,-2], colnames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)
#par(oldpar)

```

```{r}
### 因子得点のプロット(色のポジションの確認)
plot(efa$scores[,1:2], type="n", xlim=c(-2.2,2.2), ylim=c(-2.2,2.2))
text(efa$scores[,1:2], rownames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)
par(oldpar)

plot(efa$scores[,2:3], type="n", xlim=c(-2.2,2.2), ylim=c(-2.2,2.2))
text(efa$scores[,2:3], rownames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)
par(oldpar)

plot(efa$scores[,-2], type="n", xlim=c(-2.2,2.2), ylim=c(-2.2,2.2))
text(efa$scores[,-2], rownames(dat))
abline(v=0, lty=3)
abline(h=0, lty=3)
par(oldpar)
```

```{r}
# 描画
library(plotly)
plot_ly(x = as.data.frame(efa$score)$Factor1, y = as.data.frame(efa$score)$Factor2, z = as.data.frame(efa$score)$Factor3,type = 'scatter3d', symbol = rownames(dat))
```


